#Graphs for NTE1 and IDER model 12_ion figure
#When creating any sort of figures we use this IDER now without the background effect then add the background effect at the end.
IDER = function(d, L, Z.beta, eta0 = 2.487899e-04, eta1 = 8.994540e-03, sig0 = 5.956631e+00, kap = 6.950537e+02) {
  P = (1-exp(-Z.beta/kap))^2
  sig = sig0*P + 0.041/6.24*L*(1-P)
  eta = eta0*L*exp(-eta1*L)
  sig*6.24*d/L*(1-exp(-1024*d/L)) + eta*(1-exp(-10^5*d))
} 

#Comparing the NTE1 model in 16Cacao with our NASA SNTE model

#Use these dose points to generate the curves necessary. Had to include a lot more dose points at lower doses when it is very sensitive to change
d_O = c(0, 1e-6*(1:9), 1e-5*(1:9), 1e-4*(1:9), 1e-3*(1:9), 1e-2*(1:9), 0.01*(10:40))
d_1 = c(0, 1e-6*(1:9), 1e-5*(1:9), 1e-4*(1:9), 1e-3*(1:9), 1e-2*(1:9), 0.01*(10:15))

oxygen = ggplot() + geom_errorbar(data = big_df[1:9, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[1:9]*100, y = 100*big_df$CA[1:9])) + geom_line(aes(x = d_O * 100,  y = 100*(0.00071 + IDER(d = d_O, L = 75, Z.beta = 595)), col = "IDER model")) + geom_line(aes(x = d_O * 100, y = 100 * NTE1_function(d = d_O, L= 75, Z.beta = 595), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank())

oxygen_zoomout = ggplot() + geom_errorbar(data = big_df[1:7, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(aes(x = big_df$d[1:7]*100, y = 100*big_df$CA[1:7])) + geom_line(aes(x = d_1 * 100,  y = 100*(0.00071 + IDER(d = d_1, L = 75, Z.beta = 595)), col = "IDER model")) + geom_line(aes(x = d_1 * 100, y = 100*NTE1_function(d = d_1, L= 75, Z.beta = 595), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank()) + ylim(0, 4)

d_S = c(0, 1e-6*(1:9), 1e-5*(1:9), 1e-4*(1:9), 1e-3*(1:9), 1e-2*(1:9), 0.01*(10:120))

silicon = ggplot() + geom_errorbar(data = big_df[10:20, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[10:20]*100, y = 100*big_df$CA[10:20])) + geom_line(aes(x = d_S * 100,  y = 100*(0.00071 + IDER(d = d_S, L = 100, Z.beta = 690)), col = "IDER model")) + geom_line(aes(x = d_S * 100, y = 100 * NTE1_function(d = d_S, L= 100, Z.beta = 690), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank())

silicon_zoomout = ggplot() + geom_errorbar(data = big_df[10:17, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(aes(x = big_df$d[10:17]*100, y = 100*big_df$CA[10:17])) + geom_line(aes(x = d_1 * 100,  y = 100*(0.00071 + IDER(d = d_1, L = 100, Z.beta = 690)), col = "IDER model")) + geom_line(aes(x = d_1 * 100, y = 100*NTE1_function(d = d_1, L= 100, Z.beta = 690), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank()) + ylim(0, 4) + xlim(0, 15)

d_t = c(0, 1e-6*(1:9), 1e-5*(1:9), 1e-4*(1:9), 1e-3*(1:9), 1e-2*(1:9), 0.01*(10:60))

titanium = ggplot() + geom_errorbar(data = big_df[21:29, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[21:29]*100, y = 100*big_df$CA[21:29])) + geom_line(aes(x = d_t * 100,  y = 100*(0.00071 + IDER(d = d_t, L = 125, Z.beta = 770)), col = "IDER model")) + geom_line(aes(x = d_t * 100, y = 100 * NTE1_function(d = d_t, L= 125, Z.beta = 770), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank())

titanium_zoomout = ggplot() + geom_errorbar(data = big_df[21:27, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(aes(x = big_df$d[21:27]*100, y = 100*big_df$CA[21:27])) + geom_line(aes(x = d_1 * 100,  y = 100*(0.00071 + IDER(d = d_1, L = 125, Z.beta = 770)), col = "IDER model")) + geom_line(aes(x = d_1 * 100, y = 100*NTE1_function(d = d_1, L= 125, Z.beta = 770), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank()) + ylim(0, 4) + xlim(0, 15)

d_six = c(0, 1e-6*(1:9), 1e-5*(1:9), 1e-4*(1:9), 1e-3*(1:9), 1e-2*(1:9), 0.01*(10:85))

iron_six = ggplot() + geom_errorbar(data = big_df[30:40, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[30:40]*100, y = 100*big_df$CA[30:40])) + geom_line(aes(x = d_six * 100,  y = 100*(0.00071 + IDER(d = d_six, L = 175, Z.beta = 1075)), col = "IDER model")) + geom_line(aes(x = d_six * 100, y = 100 * NTE1_function(d = d_six, L= 175, Z.beta = 1075), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank())

iron_six_zoomout = ggplot() + geom_errorbar(data = big_df[30:37, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(aes(x = big_df$d[30:37]*100, y = 100*big_df$CA[30:37])) + geom_line(aes(x = d_1 * 100,  y = 100*(0.00071 + IDER(d = d_1, L = 175, Z.beta = 1075)), col = "IDER model")) + geom_line(aes(x = d_1 * 100, y = 100*NTE1_function(d = d_1, L= 175, Z.beta = 1075), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank()) + ylim(0, 4) + xlim(0, 15)

d_four = c(0, 1e-6*(1:9), 1e-5*(1:9), 1e-4*(1:9), 1e-3*(1:9), 1e-2*(1:9), 0.01*(10:45))

iron_four = ggplot() + geom_errorbar(data = big_df[41:48, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[41:48]*100, y = 100*big_df$CA[41:48])) + geom_line(aes(x = d_four * 100,  y = 100*(0.00071 + IDER(d = d_four, L = 195, Z.beta = 1245)), col = "IDER model")) + geom_line(aes(x = d_four * 100, y = 100 * NTE1_function(d = d_four, L= 195, Z.beta = 1245), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank())

iron_four_zoomout = ggplot() + geom_errorbar(data = big_df[41:46, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(aes(x = big_df$d[41:46]*100, y = 100*big_df$CA[41:46])) + geom_line(aes(x = d_1 * 100,  y = 100*(0.00071 + IDER(d = d_1, L = 195, Z.beta = 1245)), col = "IDER model")) + geom_line(aes(x = d_1 * 100, y = 100*NTE1_function(d = d_1, L= 195, Z.beta = 1245), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank()) + ylim(0, 4) + xlim(0, 15)

d_three = c(0, 1e-6*(1:9), 1e-5*(1:9), 1e-4*(1:9), 1e-3*(1:9), 1e-2*(1:9), 0.01*(10:80))

iron_three = ggplot() + geom_errorbar(data = big_df[49:58, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[49:58]*100, y = 100*big_df$CA[49:58])) + geom_line(aes(x = d_three * 100,  y = 100*(0.00071 + IDER(d = d_three, L = 240, Z.beta = 1585)), col = "IDER model")) + geom_line(aes(x = d_three * 100, y = 100 * NTE1_function(d = d_three, L= 240, Z.beta = 1585), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank())

iron_three_zoomout = ggplot() + geom_errorbar(data = big_df[49:55, ], aes(x = d*100, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(aes(x = big_df$d[49:55]*100, y = 100*big_df$CA[49:55])) + geom_line(aes(x = d_1 * 100,  y = 100*(0.00071 + IDER(d = d_1, L = 240, Z.beta = 1585)), col = "IDER model")) + geom_line(aes(x = d_1 * 100, y = 100*NTE1_function(d = d_1, L= 240, Z.beta = 1585), col = "NTE1 model"), linetype = "dotted") + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm")) + theme(axis.text.x = element_blank(), axis.text.y = element_blank()) + ylim(0, 4) + xlim(0, 15)

setEPS()
postscript("12_ions.eps", width = 10, height = 7)
grid.arrange(oxygen, silicon, titanium, oxygen_zoomout, silicon_zoomout, titanium_zoomout, iron_six, iron_four, iron_three, iron_six_zoomout, iron_four_zoomout, iron_three_zoomout, ncol = 3)
dev.off()
