#Graphs for the NTE2 and IDER model comparison in Appendix A2 (zoomed in)
#Comparing the NTE2 in 16Cacao with our NASA SNTE model
O = ggplot() + geom_errorbar(data = big_df[1:9, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[1:9], y = big_df$CA[1:9])) + geom_line(aes(x = d_O,  y = 0.00071 + IDER(d = d_O, L = 75, Z.beta = 595), col = "IDER model")) + geom_line(aes(x = d_O, y = NTE2_function(d = d_O, L= 75, Z.beta = 595), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank())

S = ggplot() + geom_errorbar(data = big_df[10:20, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[10:20], y = big_df$CA[10:20])) + geom_line(aes(x = d_S,  y = 0.00071 + IDER(d = d_S, L = 100, Z.beta = 690), col = "IDER model")) + geom_line(aes(x = d_S, y = NTE2_function(d = d_S, L= 100, Z.beta = 690), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank()) + xlim(0, 0.4) + ylim(0,0.12)

Ti = ggplot() + geom_errorbar(data = big_df[21:29, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[21:29], y = big_df$CA[21:29])) + geom_line(aes(x = d_t,  y = 0.00071 + IDER(d = d_t, L = 125, Z.beta = 770), col = "IDER model")) + geom_line(aes(x = d_t, y = NTE2_function(d = d_t, L= 125, Z.beta = 770), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank()) + xlim(0, 0.4) + ylim(0, 0.075)

i_6 = ggplot() + geom_errorbar(data = big_df[30:40, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[30:40], y = big_df$CA[30:40])) + geom_line(aes(x = d_six,  y = 0.00071 + IDER(d = d_six, L = 175, Z.beta = 1075), col = "IDER model")) + geom_line(aes(x = d_six, y = NTE2_function(d = d_six, L= 175, Z.beta = 1075), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank()) + xlim(0, 0.4) + ylim(0, 0.06)

i_4 = ggplot() + geom_errorbar(data = big_df[41:48, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[41:48], y = big_df$CA[41:48])) + geom_line(aes(x = d_four,  y = 0.00071 + IDER(d = d_four, L = 195, Z.beta = 1245), col = "IDER model")) + geom_line(aes(x = d_four, y = NTE2_function(d = d_four, L= 195, Z.beta = 1245), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank())

i_3 = ggplot() + geom_errorbar(data = big_df[49:58, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[49:58], y = big_df$CA[49:58])) + geom_line(aes(x = d_three,  y = 0.00071 + IDER(d = d_three, L = 240, Z.beta = 1585), col = "IDER model")) + geom_line(aes(x = d_three, y = NTE2_function(d = d_three, L = 240, Z.beta = 1585), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank()) + xlim(0, 0.4) + ylim(0, 0.08)

setEPS()
postscript("6_ions.eps", width = 10, height = 7)
grid.arrange(O, S, Ti, i_6, i_4, i_3, ncol = 3)
dev.off()

#Continuation for the 6 other panels of NTE2 comparison in Appendix A2 (Not zoomed in version)
#Comparing our NASA SNTE IDER model with their NTE2 IDER in 16Cacao
O = ggplot() + geom_errorbar(data = big_df[1:9, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[1:9], y = big_df$CA[1:9])) + geom_line(aes(x = d_O,  y = 0.00071 + IDER(d = d_O, L = 75, Z.beta = 595), col = "IDER model")) + geom_line(aes(x = d_O, y = NTE2_function(d = d_O, L= 75, Z.beta = 595), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank())

S = ggplot() + geom_errorbar(data = big_df[10:20, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[10:20], y = big_df$CA[10:20])) + geom_line(aes(x = d_S,  y = 0.00071 + IDER(d = d_S, L = 100, Z.beta = 690), col = "IDER model")) + geom_line(aes(x = d_S, y = NTE2_function(d = d_S, L= 100, Z.beta = 690), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank())

Ti = ggplot() + geom_errorbar(data = big_df[21:29, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[21:29], y = big_df$CA[21:29])) + geom_line(aes(x = d_t,  y = 0.00071 + IDER(d = d_t, L = 125, Z.beta = 770), col = "IDER model")) + geom_line(aes(x = d_t, y = NTE2_function(d = d_t, L= 125, Z.beta = 770), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank())

i_6 = ggplot() + geom_errorbar(data = big_df[30:40, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[30:40], y = big_df$CA[30:40])) + geom_line(aes(x = d_six,  y = 0.00071 + IDER(d = d_six, L = 175, Z.beta = 1075), col = "IDER model")) + geom_line(aes(x = d_six, y = NTE2_function(d = d_six, L= 175, Z.beta = 1075), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank())

i_4 = ggplot() + geom_errorbar(data = big_df[41:48, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[41:48], y = big_df$CA[41:48])) + geom_line(aes(x = d_four,  y = 0.00071 + IDER(d = d_four, L = 195, Z.beta = 1245), col = "IDER model")) + geom_line(aes(x = d_four, y = NTE2_function(d = d_four, L= 195, Z.beta = 1245), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank())

i_3 = ggplot() + geom_errorbar(data = big_df[49:58, ], aes(x = d, ymin = errorbar_lower, ymax = errorbar_upper), col = "black", width = 0)  + geom_point(aes(x = big_df$d[49:58], y = big_df$CA[49:58])) + geom_line(aes(x = d_three,  y = 0.00071 + IDER(d = d_three, L = 240, Z.beta = 1585), col = "IDER model")) + geom_line(aes(x = d_three, y = NTE2_function(d = d_three, L = 240, Z.beta = 1585), col = "NTE2 model"), linetype = 2) + labs(x = "", y = "", title = "") + scale_colour_manual(guide = FALSE, name = "Models", values = c("red", "blue"), label = c("IDER", "NTE1")) + theme_bw() + theme(axis.line.x = element_line(color="black", size = 0.3), axis.line.y = element_line(color="black", size = 0.3), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.y = element_line(size = 0.3), axis.ticks.x = element_line(size = 0.3), axis.text=element_text(size=12), axis.title=element_text(size=14), axis.ticks.length = unit(0.3, "cm"), axis.text.x = element_blank(), axis.text.y = element_blank(), panel.border = element_blank())

setEPS()
postscript("6_ions_2.eps", width = 10, height = 7)
grid.arrange(O, S, Ti, i_6, i_4, i_3, ncol = 3)
dev.off()