###Creating Figure 2: Zoomed in IDERs for all Models
oxygen_comp = ggplot() +  geom_line(aes(x = d_oxygen, y = 100*two_IDER(d = d_oxygen, L = 75)), col = "green", size = 5)+ geom_line(aes(x = d_oxygen, y = 100*three_IDER_no_kap(d = d_oxygen, L = 75)), col = "black", size = 1)+ geom_line(aes(x = d_oxygen, y = 100*original_IDER(d = d_oxygen, L = 75, Z.beta= 595)), col = "red", size = 1.4)  + geom_line(aes(x = d_oxygen, y = 100*three_IDER_no_eta1(d = d_oxygen, L = 75, Z.beta = 595)), col = "black", linetype = "dotted", size = 3.5) + labs(x = "Dose (Gy)", y = "Prevalence (%)", title = "O") + geom_errorbar(data = big_df[big_df[, 7] == "O", ][-1, ], aes(x = d, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(data = big_df[big_df[, 7] == "O", ][-1, ], aes(x = d, y = 100*CA), size = 10) + geom_line(aes(x = d_oxygen, y = 100*TE_IDER(d = d_oxygen, L = 75, Z.beta = 595)), col = "purple", size = 1) + theme(axis.text=element_text(size=10))  + annotate("text",x = 0.015, y = 3.3, label = "atop(bold('A'))", size = 20, parse = TRUE) + theme(axis.text=element_text(size=35), axis.title=element_text(size=75), plot.title = element_text(size=84), plot.margin = margin(10, 10, 30, 120), axis.title.y = element_text(vjust = 20)) + scale_x_continuous(breaks = c(0, 0.1), limits = c(0, 0.1)) + ylim(0, 4) 

si_comp = ggplot()  + geom_line(aes(x = d_si, y = 100*two_IDER(d = d_si, L = 100)), col = "green", size = 3) +geom_line(aes(x = d_si, y = 100*three_IDER_no_kap(d = d_si, L = 100)),col = "black", size = 1) +geom_line(aes(x = d_si, y = 100*original_IDER(d = d_si, L = 100, Z.beta= 690)), col = "red", size = 1.4) + geom_line(aes(x = d_si, y = 100*three_IDER_no_eta1(d = d_si, L = 100, Z.beta = 690)), col = "black", linetype = "dotted", size = 3.5)  + labs(x = "Dose (Gy)", y = "", title = "Si") + geom_errorbar(data = big_df[big_df[, 7] == "Si", ][-1, ], aes(x = d, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(data = big_df[big_df[, 7] == "Si", ][-1, ], aes(x = d, y =100* CA), size = 10) + geom_line(aes(x = d_si, y = 100*TE_IDER(d = d_si, L = 100, Z.beta = 690)), col = "purple", size = 1) + annotate("text",x = 0.015, y = 2.1, label = "atop(bold('B'))", size = 20, parse = TRUE) +  theme(axis.text=element_text(size=35), axis.title=element_text(size=75), plot.title =element_text(size=84), plot.margin = margin(10, 10, 30, 120), axis.title.y = element_text(vjust = 30)) + scale_x_continuous(breaks = c(0, 0.1), limits = c(0, 0.1))+ ylim(0, 2.5)

ti_comp = ggplot() + geom_line(aes(x = d_ti, y = 100*two_IDER(d = d_ti, L = 125)), col = "green", size = 5) + geom_line(aes(x = d_ti, y = 100*three_IDER_no_kap(d = d_ti, L = 125)), col = "black", size = 1)+ geom_line(aes(x = d_ti, y = 100*original_IDER(d = d_ti, L = 125, Z.beta= 770)), col = "red", size = 1.4) + geom_line(aes(x = d_ti, y = 100*three_IDER_no_eta1(d = d_ti, L = 125, Z.beta = 770)), col = "black", linetype = "dotted", size = 3.5)  + labs(x = "Dose (Gy)", y = "", title = "Ti") + geom_errorbar(data = big_df[big_df[, 7] == "Ti", ][-1, ], aes(x = d, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(data = big_df[big_df[, 7] == "Ti", ][-1, ], aes(x = d, y = 100*CA), size = 10) + geom_line(aes(x = d_ti, y = 100*TE_IDER(d = d_ti, L = 125, Z.beta = 770)), col = "purple", size = 1)+ theme(axis.text=element_text(size=10)) + annotate("text",x = 0.015, y = 3.4, label = "atop(bold('C'))", size = 20, parse = TRUE) + theme(axis.text=element_text(size=35), axis.title=element_text(size=75), plot.title =element_text(size=84), plot.margin = margin(10, 10, 30, 120),  axis.title.y = element_text(vjust = 30))  + scale_x_continuous(breaks = c(0, 0.1), limits = c(0, 0.1)) + ylim(0, 4) 

fe300_comp =  ggplot() +geom_line(aes(x = d_fe300, y = 100*two_IDER(d = d_fe300, L = 175)), col = "green", size = 5) +  geom_line(aes(x = d_fe300, y = 100*three_IDER_no_kap(d = d_fe300, L = 175)), col = "black", size = 1) + geom_line(aes(x = d_fe300, y = 100*original_IDER(d = d_fe300, L = 175, Z.beta= 1075)), col = "red",size = 1.4)  + geom_line(aes(x = d_fe300, y = 100*three_IDER_no_eta1(d = d_fe300, L = 175, Z.beta = 1075)), col = "black", linetype = "dotted", size = 3.5) + labs(x = "Dose (Gy)", y = "", title = "Fe0.65") + geom_errorbar(data = big_df[big_df[, 7] == "Fe300", ][-1, ], aes(x = d, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(data = big_df[big_df[, 7] == "Fe300", ][-1, ], aes(x = d, y = 100*CA), size = 10) + geom_line(aes(x = d_fe300, y = 100*TE_IDER(d = d_fe300, L = 175, Z.beta = 1075)), col = "purple", size = 1) + annotate("text",x = 0.015, y = 2.5, label = "atop(bold('D'))", size = 20, parse = TRUE) + theme(axis.text=element_text(size=35), axis.title=element_text(size=75), plot.title =element_text(size=84), plot.margin = margin(10, 10, 30, 120),  axis.title.y = element_text(vjust = 30)) + scale_x_continuous(breaks = c(0, 0.1), limits = c(0, 0.1)) + ylim(0, 3)

fe450_comp = ggplot() + geom_line(aes(x = d_fe450, y = 100*two_IDER(d = d_fe450, L = 195)), col = "green", size = 5) + geom_line(aes(x = d_fe450, y = 100*three_IDER_no_kap(d = d_fe450, L = 195)), col = "black", size = 1) + geom_line(aes(x = d_fe450, y = 100*original_IDER(d = d_fe450, L = 195, Z.beta= 1245)), col = "red", size = 1.4)  + geom_line(aes(x = d_fe450, y = 100*three_IDER_no_eta1(d = d_fe450, L = 195, Z.beta = 1245)), col = "black", linetype = "dotted", size = 3.5) +  labs(x = "Dose (Gy)", y = "", title = "Fe0.74") + geom_errorbar(data = big_df[big_df[, 7] == "Fe450", ][-1, ], aes(x = d, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(data = big_df[big_df[, 7] == "Fe450", ][-1, ], aes(x = d, y = 100*CA), size = 10) + geom_line(aes(x = d_fe450, y = 100*TE_IDER(d = d_fe450, L = 195, Z.beta = 1245)), col = "purple", size = 1) + annotate("text",x = 0.015, y = 2.5, label = "atop(bold('E'))", size = 20, parse = TRUE) + theme(axis.text=element_text(size=35), axis.title=element_text(size=75), plot.title =element_text(size=84), plot.margin = margin(10, 10, 30, 120),  axis.title.y = element_text(vjust = 30)) + scale_x_continuous(breaks = c(0, 0.1), limits = c(0, 0.1)) + ylim(0, 3) 

fe600_comp = ggplot()  + labs(x = "Dose (Gy)", y = "", title = "Fe0.79") + geom_line(aes(x = d_fe600, y = 100*two_IDER(d = d_fe600, L = 240)), col = "green", size = 5)+ geom_line(aes(x = d_fe600, y = 100*three_IDER_no_kap(d = d_fe600, L = 240)), col = "black", size = 1)  + geom_line(aes(x = d_fe600, y = 100*original_IDER(d = d_fe600, L = 240, Z.beta= 1585)), col = "red", size = 1.4) + geom_line(aes(x = d_fe600, y = 100*three_IDER_no_eta1(d = d_fe600, L = 240, Z.beta = 1585)), col = "black", linetype = "dotted", size = 3.5) + geom_errorbar(data = big_df[big_df[, 7] == "Fe600", ][-1, ], aes(x = d, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(data = big_df[big_df[, 7] == "Fe600", ][-1, ], aes(x = d, y = 100*CA), size = 10) + geom_line(aes(x = d_fe600, y = 100*TE_IDER(d = d_fe600, L = 240, Z.beta = 1585)), col = "purple", size = 1) + annotate("text",x =0.015, y = 2.1, label = "atop(bold('F'))", size = 20, parse = TRUE) + theme(axis.text=element_text(size=35), axis.title=element_text(size=75), plot.title =element_text(size=84), plot.margin = margin(10, 10, 30, 120),  axis.title.y = element_text(vjust = 30)) + scale_x_continuous(breaks = c(0, 0.1), limits = c(0, 0.1)) + ylim(0, 2.5) 

oxygen = ggplotGrob(oxygen_comp)
si = ggplotGrob(si_comp)
ti = ggplotGrob(ti_comp)
fe300 = ggplotGrob(fe300_comp)
fe450 = ggplotGrob(fe450_comp)
fe600 = ggplotGrob(fe600_comp)

si$heights = oxygen$heights
si$widths = oxygen$widths

ti$heights = oxygen$heights
ti$widths = oxygen$widths

fe450$heights = fe300$heights
fe450$widths = fe300$widths

fe600$heights = fe450$heights
fe600$widths = fe450$widths

pdf("IDER_fig_zoomedinx2.pdf", width = 60, height = 15)
grid.arrange(oxygen_comp, si_comp, ti_comp, fe300_comp, fe450_comp, fe600_comp, nrow = 1)
dev.off()


si_comp = ggplot()  + geom_line(aes(x = d_si, y = 100*two_IDER(d = d_si, L = 100)), col = "green", size = 3) +geom_line(aes(x = d_si, y = 100*three_IDER_no_kap(d = d_si, L = 100)),col = "black", size = 1) +geom_line(aes(x = d_si, y = 100*original_IDER(d = d_si, L = 100, Z.beta= 690)), col = "red", size = 1.4) + geom_line(aes(x = d_si, y = 100*three_IDER_no_eta1(d = d_si, L = 100, Z.beta = 690)), col = "black", linetype = "dotted", size = 3.5)  + labs(x = "Dose (Gy)", y = "", title = "Si") + geom_errorbar(data = big_df[big_df[, 7] == "Si", ][-1, ], aes(x = d, ymin = 100*errorbar_lower, ymax = 100*errorbar_upper), col = "black", width = 0) + geom_point(data = big_df[big_df[, 7] == "Si", ][-1, ], aes(x = d, y =100* CA), size = 10) + geom_line(aes(x = d_si, y = 100*TE_IDER(d = d_si, L = 100, Z.beta = 690)), col = "purple", size = 1) + annotate("text",x = 0.015, y = 2.1, label = "atop(bold('B'))", size = 20, parse = TRUE) +  theme(axis.text=element_text(size=35), axis.title=element_text(size=75), plot.title =element_text(size=84), plot.margin = margin(10, 10, 30, 120), axis.title.y = element_text(vjust = 30)) 

pdf("si_graph.pdf")
si_comp
dev.off()